In [1]:
%load_ext dotenv
%dotenv

In [3]:
from langchain_openai import OpenAIEmbeddings
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Initialize the OpenAI Embeddings
embeddings = OpenAIEmbeddings()

# Words to embed
words = ["Kot", "Pies", "Ala ma kota"]

# Get embeddings
embedded_words = embeddings.embed_documents(words)

# Print the embeddings
for word, embedding in zip(words, embedded_words):
    print(f"Embedding for '{word}':")
    print(np.array(embedding[:5]))  # Print first 5 dimensions for brevity
    print()

# Calculate cosine similarities
kot_pies_similarity = cosine_similarity([embedded_words[0]], [embedded_words[1]])[0][0]
kot_ala_similarity = cosine_similarity([embedded_words[0]], [embedded_words[2]])[0][0]
pies_ala_similarity = cosine_similarity([embedded_words[1]], [embedded_words[2]])[0][0]

print("Cosine Similarities:")
print(f"'Kot' and 'Pies': {kot_pies_similarity:.4f}")
print(f"'Kot' and 'Ala ma kota': {kot_ala_similarity:.4f}")
print(f"'Pies' and 'Ala ma kota': {pies_ala_similarity:.4f}")

Embedding for 'Kot':
[ 0.00134297 -0.0212902  -0.00746932  0.00052272 -0.00777178]

Embedding for 'Pies':
[ 0.01242397 -0.02552266  0.01039332 -0.02243451 -0.02068283]

Embedding for 'Ala ma kota':
[ 0.01203457  0.00885123 -0.01089582  0.00514381 -0.02821007]

Cosine Similarities:
'Kot' and 'Pies': 0.7849
'Kot' and 'Ala ma kota': 0.8488
'Pies' and 'Ala ma kota': 0.7670


In [4]:
# Words to embed
words = ["Plus", "Minus",]

# Get embeddings
embedded_words = embeddings.embed_documents(words)

# Print the embeddings
for word, embedding in zip(words, embedded_words):
    print(f"Embedding for '{word}':")
    print(np.array(embedding[:5]))  # Print first 5 dimensions for brevity
    print()

# Calculate cosine similarities
plus_minus_similarity = cosine_similarity([embedded_words[0]], [embedded_words[1]])[0][0]

print("Cosine Similarities:")
print(f"'Plus' and 'Minus': {plus_minus_similarity:.4f}")


Embedding for 'Plus':
[-0.00524198 -0.00443823  0.00393413 -0.01707609 -0.03736717]

Embedding for 'Minus':
[ 0.00410642 -0.00662594  0.0210237  -0.00531738 -0.02197801]

Cosine Similarities:
'Plus' and 'Minus': 0.9133


In [5]:
# Words to embed
words = ["Good", "Bad",]

# Get embeddings
embedded_words = embeddings.embed_documents(words)

# Print the embeddings
for word, embedding in zip(words, embedded_words):
    print(f"Embedding for '{word}':")
    print(np.array(embedding[:5]))  # Print first 5 dimensions for brevity
    print()

# Calculate cosine similarities
good_bad_similarity = cosine_similarity([embedded_words[0]], [embedded_words[1]])[0][0]

print("Cosine Similarities:")
print(f"'Good' and 'Bad': {good_bad_similarity:.4f}")


Embedding for 'Good':
[-0.0028408  -0.01831893  0.01161022 -0.02305143 -0.03099526]

Embedding for 'Bad':
[-0.0189193   0.00116218  0.00905739 -0.01672632 -0.02748359]

Cosine Similarities:
'Good' and 'Bad': 0.9016


In [8]:
# Words to embed
words = ["Informacje o borderach", "Wybrana rasa psów to Border Collie. Border Collie to jedna z najbardziej inteligentnych i pracowitych ras na świecie, często uznawana za najlepszą w pasieniu owiec. Pochodzą z Wielkiej Brytanii, gdzie przez wieki wykorzystywano je do pracy na farmach. Psy te są pełne energii i potrzebują dużo ruchu, co czyni je idealnymi towarzyszami dla aktywnych osób. Ich instynkt pracy oraz silne przywiązanie do opiekuna sprawiają, że są łatwe do szkolenia, choć wymagają konsekwentnego i doświadczonego właściciela. Border Collie to także rasa, która doskonale sprawdza się w różnych sportach kynologicznych, takich jak agility czy obedience. Pomimo ich przyjacielskiego charakteru, mogą być nieco nieśmiałe wobec obcych", "Wybrana rasa to Siberian Husky. Husky syberyjski to rasa psa pierwotnie hodowana do ciągnięcia sań na dalekiej północy, znana ze swojej wytrzymałości i energii. Pochodzą z Syberii, gdzie przez wieki były nieodłącznymi towarzyszami rdzennych plemion, pomagając w transporcie i polowaniach. Husky wyróżnia się charakterystycznym, wilczym wyglądem, często ma niebieskie lub różnobarwne oczy oraz gęstą, podwójną sierść, która chroni go przed mrozem. Są to psy bardzo niezależne, ale jednocześnie przyjazne i towarzyskie. Potrzebują dużo ruchu, ponieważ ich naturalna energia wymaga intensywnej aktywności fizycznej. Husky to także rasa, która rzadko szczeka, ale wydaje charakterystyczne wycie, co jest pozostałością po ich wilczych przodkach."]

# Get embeddings
embedded_words = embeddings.embed_documents(words)

# Print the embeddings
for word, embedding in zip(words, embedded_words):
    print(f"Embedding for '{word}':")
    print(np.array(embedding[:5]))  # Print first 5 dimensions for brevity
    print()

# Calculate cosine similarities
border_border_text_similarity = cosine_similarity([embedded_words[0]], [embedded_words[1]])[0][0]
border_husky_text_similarity = cosine_similarity([embedded_words[0]], [embedded_words[2]])[0][0]

print("Cosine Similarities:")
print(f"'Border' and 'Border': {border_border_text_similarity:.4f}")
print(f"'Border' and 'Husky': {border_husky_text_similarity:.4f}")


Embedding for 'Informacje o borderach':
[-0.00708543  0.01598296  0.00598709 -0.01093777 -0.02714236]

Embedding for 'Wybrana rasa psów to Border Collie. Border Collie to jedna z najbardziej inteligentnych i pracowitych ras na świecie, często uznawana za najlepszą w pasieniu owiec. Pochodzą z Wielkiej Brytanii, gdzie przez wieki wykorzystywano je do pracy na farmach. Psy te są pełne energii i potrzebują dużo ruchu, co czyni je idealnymi towarzyszami dla aktywnych osób. Ich instynkt pracy oraz silne przywiązanie do opiekuna sprawiają, że są łatwe do szkolenia, choć wymagają konsekwentnego i doświadczonego właściciela. Border Collie to także rasa, która doskonale sprawdza się w różnych sportach kynologicznych, takich jak agility czy obedience. Pomimo ich przyjacielskiego charakteru, mogą być nieco nieśmiałe wobec obcych':
[-0.00997437  0.01056408 -0.01771671 -0.03568707 -0.02479325]

Embedding for 'Wybrana rasa to Siberian Husky. Husky syberyjski to rasa psa pierwotnie hodowana do ciągni